/**
 * Auth.js route handler.
 *
 * Re-exports the GET/POST handlers generated by the NextAuth() call in
 * `@/auth`. All Auth.js endpoints (sign-in, callback, sign-out, session)
 * are served from /api/auth/*.
 */
import { handlers } from "@/auth";

export const { GET, POST } = handlers;
